# Generated by Django 5.1.7 on 2025-03-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_date_remove_product_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_size',
            field=models.IntegerField(choices=[(39, 'Size 1'), (40, 'Size 2'), (41, 'Size 3'), (42, 'Size 4'), (43, 'Size 5'), (44, 'Size 6')], default=39, verbose_name='Размер'),
        ),
    ]
