# Generated by Django 5.1.7 on 2025-03-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_size',
            field=models.CharField(choices=[('1', '39'), ('2', '40'), ('3', '41'), ('4', '42'), ('5', '43'), ('6', '44')], default='1', max_length=20, verbose_name='Размер'),
        ),
    ]
